export const AD_EDIT_STYLE = {
  version: 2,
  label: {
    fontSize: 68,
    minFontSize: 64,
    maxFontSize: 72,
    supportingFontSize: 48,
    letterSpacingEm: -0.02,
    horizontalPaddingEm: 0.8,
    heightEm: 2,
    maxWidthRatio: 0.8,
    safeSide: 0.04,
    safeTop: 0.1,
    bottomRatio: 0.69,
    olive: "#3E4A22",
    white: "#FFFDF5",
    gold: "#B09A60",
    linePx: 5,
    lineBorderPx: 2,
    anchorRadiusPx: 13,
    anchorBorderPx: 4,
    maxLeaderReachRatio: 0.15,
    growSec: 0.4,
  },
  caption: {
    normalPx: 64,
    pointPx: 86,
    centerY: 1464,
    chestY: 1228,
    widthRatio: 0.8,
    white: "FFFDF5",
    accent: "FFF8CC",
    outline: "17251C",
  },
  // Source retains 40ms before speech and 100ms after; 150ms file spacing targets ~290ms audible pauses.
  pacing: { gapMs: 150, tailMs: 150, maxGapMs: 600 },
} as const;
